hug_links = [
    "https://tenor.com/view/cat-hugs-alydn-gif-26454086",
    "https://tenor.com/view/hug-love-hi-bye-cat-gif-15999080",
    "https://tenor.com/view/covid-meme-cute-gif-23513805",
    "https://tenor.com/view/dog-gif-25785273",
    "https://tenor.com/view/lick-kiss-smooch-affection-dog-gif-16669611",
    "https://tenor.com/view/polar-bear-baby-hug-gif-26055063",
    "https://tenor.com/view/cat-love-huge-hug-big-gif-11990658",
    "https://tenor.com/view/hugh-hug-cathug-cathugh-cute-gif-21970142",
    "https://tenor.com/view/cat-hug-cat-hug-cute-love-gif-23090693",
    "https://tenor.com/view/heejake-gif-24738397"
]

# All matches are case-insensitive and are anchored at the beginning but not the end of the string. `<user>`
# (without the quotes) denotes a user mention. Textual representations of emojis as used in the `emojis` PyPi package
# (e.g., :red_heart:) as well as emojis themselves are allowed. Because some emojis look identical but have different
# binary representations, it is recommended that only textual representations be used in the patterns.
[patterns."<user>?(, )?(good morning)(?!\\S)"]
reactions = [":sun:"]
responses = ["Good morning to you, too!"]

[patterns."<user>?(, )?(g(ood ?)?ni(ght|te)|sleep well|gn|night)(?!\\S)"]
reactions = [":sleeping_face:", ":crescent_moon:", ':ZZZ:', ':yawning_face:']
responses = ["Sweet dreams! ~", "Good nighty! :relieved_face:"]

[patterns."<user>?(, )?(hello|hi|sup|what'?s up\\?|have a great day)(?!\\S)"]
reactions = [":waving_hand:", ":smiling_face_with_smiling_eyes:"]
responses = []

[patterns."<user>?(, )?(bye|fare well|see (you|u|ya)|cya|l(at|8)er|(cu|c u)!?|talk to you (\\w* )?later)(?!\\S)"]
reactions = [":waving_hand:"]
responses = ["Take care!", "See you around!", "Hope to see you back, soon!"]

[patterns."<user>?(, )?((I )?(love|:red_heart:) (you|u|ya)|hug)(?!\\S)"]
reactions = [":red_heart:", ":heart_on_fire:", ":revolving_hearts:"]
responses = ["Aww!", "You're sweet!", "Cute ~"]

[patterns."<user>?(, )?((I|we )?(thank (you|u|ya))|thankies|thanks)(?!\\S)"]
reactions = [":OK_hand:", ":face_with_steam_from_nose:"]
responses = []
