hug_links = [
    "https://tenor.com/view/cat-hugs-alydn-gif-26454086",
    "https://tenor.com/view/hug-love-hi-bye-cat-gif-15999080",
    "https://tenor.com/view/covid-meme-cute-gif-23513805",
    "https://tenor.com/view/dog-gif-25785273",
    "https://tenor.com/view/lick-kiss-smooch-affection-dog-gif-16669611",
    "https://tenor.com/view/polar-bear-baby-hug-gif-26055063",
    "https://tenor.com/view/cat-love-huge-hug-big-gif-11990658",
    "https://tenor.com/view/hugh-hug-cathug-cathugh-cute-gif-21970142",
    "https://tenor.com/view/cat-hug-cat-hug-cute-love-gif-23090693",
    "https://tenor.com/view/heejake-gif-24738397"
]

# All matches are case-insensitive, not anchored, and automatically don't match if there is a non-whitespace at the
# beginning or end of the pattern, except for the characters `,`, `.`, and `!` if they are at the end of the pattern.
# `<user>` (without the quotes) denotes a user mention. Textual representations of emojis as used in the `emojis` PyPi
# package (e.g., :red_heart:) as well as emojis themselves are allowed. Because some emojis look identical but have
# different binary representations, it is recommended that only textual representations be used in the patterns.
# `chance` is a number between 0.0 and 1.0. and represents the chance the bot will respond to a match. If left out, it
# defaults to 1.0.

[patterns."g(ood )morn(ing)"]
reactions = [":sun:"]
responses = [
    "Good morning to you, too!",
    "Seize the day.",
    "You've got this!",
    "I believe in you. The day lies in your hands.",
    "Carpe diem!"
]

[patterns."g(n|((ood ?)?ni(ght|te)))|sleep well"]
reactions = [":sleeping_face:", ":crescent_moon:", ':ZZZ:', ':yawning_face:']
responses = [
    "Sweet dreams! ~",
    "Good nighty! :relieved_face:",
    "You get one wish. :shooting_star:",
    "Don't stay any longer, you need the energy for tomorrow.",
    "Make sure you've prepared everything you need for tomorrow.",
    "Before you go to sleep, take a moment and reflect on the things that went well today, and those that didn't.",
    "I'm also getting tired. :yawning_face:"
]

[patterns."h?ello|hi|sup|what'?s up\\?|have a (g(reat|ood)|nice) day"]
reactions = [":waving_hand:", ":smiling_face_with_smiling_eyes:"]
responses = []
chance = 0.4

[patterns."bye|fare well|(see |c ?)(y(ou|a)|u)!?|talk to (y(ou|a)|u) l(at|8)er"]
reactions = [":waving_hand:"]
responses = ["Take care!", "See you around!", "Hope to see you back, soon!"]

[patterns."(love|:red_heart:) (y(ou|a)|u)|hug"]
reactions = [":red_heart:", ":heart_on_fire:", ":revolving_hearts:"]
responses = ["Aww!", "You're sweet!", "Cute ~"]

[patterns."(t(y|(hank( (y(ou|a)|u)|(ie)?s))))"]
reactions = [":OK_hand:", ":smiling_face_with_smiling_eyes:"]
responses = []
chance = 0.4
